export const SELECT_SERIES = 'SELECT_SERIES';
export const UNSELECT_SERIES = 'UNSELECT_SERIES';
export const SELECT_REGION = 'SELECT_REGION';
export const UNSELECT_REGION = 'UNSELECT_REGION';
export const SELECT_SUBREGION = 'SELECT_SUBREGION';
export const UNSELECT_SUBREGION = 'UNSELECT_SUBREGION';

export const REQUEST_SERIES_LIST = "REQUEST_SERIES_LIST";
export const REQUEST_GEOCODING = "REQUEST_GEOCODING";
export const REQUEST_GEOLOCATION = "REQUEST_GEOLOCATION";
export const REQUEST_REGIONS = "REQUEST_REGIONS";
export const REQUEST_REGION = "REQUEST_REGION";
export const REQUEST_SERIES_BY_GEOLOCATION = "REQUEST_SERIES_BY_GEOLOCATION";
export const REQUEST_SERIES_BY_REGION_ID = "REQUEST_SERIES_BY_REGION_ID";

export const RECEIVE_SERIES_LIST = "RECEIVE_SERIES_LIST";
export const RECEIVE_GEOCODING = "RECEIVE_GEOCODING";
export const RECEIVE_GEOLOCATION = "RECEIVE_GEOLOCATION";
export const RECEIVE_REGIONS = 'RECEIVE_REGIONS';
export const RECEIVE_REGION = "RECEIVE_REGION";
export const RECEIVE_SERIES = 'RECEIVE_SERIES';
