export const SELECT_REGION = 'SELECT_REGION';
export const UNSELECT_REGION = 'UNSELECT_REGION';
export const SELECT_MUNICIPALITY = 'SELECT_MUNICIPALITY';
export const UNSELECT_MUNICIPALITY = 'UNSELECT_MUNICIPALITY';

export const REQUEST_GEOCODING = "REQUEST_GEOCODING";
export const REQUEST_GEOLOCATION = "REQUEST_GEOLOCATION";
export const REQUEST_REGIONS = "REQUEST_REGIONS";
export const REQUEST_MUNICIPALITIES = "REQUEST_MUNICIPALITIES";
export const REQUEST_CASES_BY_GEOLOCATION = "REQUEST_CASES_BY_GEOLOCATION";
export const REQUEST_CASES_BY_REGION_ID = "REQUEST_CASES_BY_REGION_ID";
export const REQUEST_CASES_BY_MUNICIPALITY_ID = "REQUEST_CASES_BY_MUNICIPALITY_ID";

export const RECEIVE_GEOCODING = "RECEIVE_GEOCODING";
export const RECEIVE_GEOLOCATION = "RECEIVE_GEOLOCATION";
export const RECEIVE_REGIONS = 'RECEIVE_REGIONS';
export const RECEIVE_MUNICIPALITIES = "RECEIVE_MUNICIPALITIES";
export const RECEIVE_CASES = 'RECEIVE_CASES';
