export const SELECT_SERIES = 'SELECT_SERIES';
export const UNSELECT_SERIES = 'UNSELECT_SERIES';
export const SELECT_REGION = 'SELECT_REGION';
export const UNSELECT_REGION = 'UNSELECT_REGION';
export const SET_FILTER_OPTIONS = "SET_FILTER_OPTIONS";
export const SELECT_DASHBOARD_TAB = 'SELECT_DASHBOARD_TAB';

export const REQUEST_SERIES_LIST = "REQUEST_SERIES_LIST";
export const REQUEST_GEOLOCATION = "REQUEST_GEOLOCATION";
export const REQUEST_REGIONS = "REQUEST_REGIONS";
export const REQUEST_REGION = "REQUEST_REGION";
export const REQUEST_SUBREGIONS = "REQUEST_SUBREGIONS";
export const REQUEST_SERIES_BY_REGION_ID = "REQUEST_SERIES_BY_REGION_ID";
export const REQUEST_REGION_BY_GEOLOCATION = "REQUEST_REGION_BY_GEOLOCATION";

export const RECEIVE_SERIES_LIST = "RECEIVE_SERIES_LIST";
export const RECEIVE_GEOLOCATION = "RECEIVE_GEOLOCATION";
export const RECEIVE_REGIONS = 'RECEIVE_REGIONS';
export const RECEIVE_REGION = "RECEIVE_REGION";
export const RECEIVE_SUBREGIONS = "RECEIVE_SUBREGIONS";
export const RECEIVE_SERIES = 'RECEIVE_SERIES';

export const ERROR_GEOLOCATION = "ERROR_GEOLOCATION";
export const ERROR_LOADING = "ERROR_LOADING";

export const SET_DEFAULT_LOCATION = "SET_DEFAULT_LOCATION";

export const SELECT_THEME = "SELECT_THEME";
export const TOGGLE_THEME = "TOGGLE_THEME";
